import org.gradle.api.tasks.bundling.AbstractArchiveTask

plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
}

version = "${project.mod_version}+${project.minecraft_version}"

repositories {
    // Loom provides the Minecraft and Fabric repositories.
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "buttcraft" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

sourceSets {
    main {
        resources {
            srcDir "../common/resources"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    def version = project.version
    def minecraftVersion = project.minecraft_version
    def loaderVersion = project.loader_version
    def javaVersion = project.java_version

    inputs.property "version", version
    inputs.property "minecraft_version", minecraftVersion
    inputs.property "loader_version", loaderVersion
    inputs.property "java_version", javaVersion

    filesMatching("fabric.mod.json") {
        expand(
            "version": version,
            "minecraft_version": minecraftVersion,
            "loader_version": loaderVersion,
            "java_version": javaVersion
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(AbstractArchiveTask).configureEach {
    archiveBaseName = "buttcraft"
}

jar {
    from("LICENSE") {
        rename { "${it}_buttcraft" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }

    repositories {
        // Add publishing repositories here if needed.
    }
}